import { Project } from "@/types/project";

export const mockProjects: Project[] = [
    {
      project_id: 1314,
      id: "1",
      name: "Libft",
      description:
        "This project is your very first project as a student at 42. You will need to recode a few functions of the C standard library as well as some other utility functions that you will use during your whole cursus.",
      difficulty: "beginner",
      estimatedHours: 70,
      baseXP: 462,
      teamSize: { min: 1, max: 1 },
      subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/147564/en.subject.pdf",
      status: "completed",
      tags: ["Unix logic", "Rigor", "Algorithms & AI", "Imperative programming"],
      updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1316,
      id: "2",
      name: "ft_printf",
      description:
        "This project is pretty straightforward, you have to recode printf. You will learn what is and how to implement variadic functions. Once you validate it, you will reuse this function in your future projects.",
      difficulty: "beginner",
      estimatedHours: 70,
      baseXP: 882,
      teamSize: { min: 1, max: 1 },
      subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/147351/en.subject.pdf",
      status: "completed",
      tags: ["Unix logic", "Rigor", "Algorithms & AI"],
      updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1327,
      id: "3",
      name: "get_next_line",
      description:
        "May it be a file, stdin, or even later a network connection, you will always need a way to read content line by line. It is time to start working on this function, which will be essential for your future projects.",
      difficulty: "beginner",
      estimatedHours: 70,
      baseXP: 882,
      teamSize: { min: 1, max: 1 },
      subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/147230/en.subject.pdf",
      status: "completed",
      tags: ["Unix logic", "Rigor", "Unix", "Algorithms & AI"],
      updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1994,
      id: "4",
      name: "Born2beroot",
      description:
        "This project aims to introduce you to the wonderful world of virtualization.",
      difficulty: "beginner",
      estimatedHours: 70,
      baseXP: 882,
      teamSize: { min: 1, max: 1 },
      subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/147358/en.subject.pdf",
      status: "completed",
      tags: ["Rigor", "Network & system administration"],
      updatedAt: new Date().toISOString(),
    },
    {
      project_id: 2005,
      id: "5",
      name: "minitalk",
      description:
        "The purpose of this project is to code a small data exchange program using UNIX signals. It is an introductory project for the bigger UNIX projects that will appear later on in the cursus.",
      difficulty: "beginner",
      estimatedHours: 50,
      baseXP: 1142,
      teamSize: { min: 1, max: 1 },
      subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/136339/en.subject.pdf",
      status: "completed",
      tags: ["Applicative"],
      updatedAt: new Date().toISOString(),
    },
    {
      project_id: 2004,
      id: "6",
      name: "pipex",
      description:
        "This project aims to deepen your understanding of the two concepts that you already know: Redirections and Pipes. It is an introductory project for the bigger UNIX projects that will appear later on in the cursus.",
      difficulty: "beginner",
      estimatedHours: 50,
      baseXP: 1142,
      teamSize: { min: 1, max: 1 },
      subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/147342/en.subject.pdf",
      status: "not_started",
      tags: ["Unix logic", "Unix", "Imperative programming"],
      updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1476,
      id: "7",
      name: "fract-ol",
      description:
        "Discover 2D programming and the psychedelic universe of fractals in this project, using minilibX.",
      difficulty: "beginner",
      estimatedHours: 60,
      baseXP: 1000,
      teamSize: { min: 1, max: 1 },
      subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/143919/en.subject.pdf",
      status: "not_started",
      tags: ["2D programming", "Optimization techniques", "Some Maths", "Imperative programming", "Graphics"],
      updatedAt: new Date().toISOString(),
    },
    {
      project_id: 2009,
      id: "8",
      name: "so_long",
      description:
        "This project is a small 2D game with minilibx. You'll learn about textures, sprites and tiles.",
      difficulty: "beginner",
      estimatedHours: 60,
      baseXP: 1000,
      teamSize: { min: 1, max: 1 },
      subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/136352/en.subject.pdf",
      status: "completed",
      tags: ["Applicative", "Imperative programming", "Graphics"],
      updatedAt: new Date().toISOString(),
    },
    {
      project_id: 2008,
      id: "9",
      name: "FdF",
      description:
        "All programs that you wrote until now were executed in text mode on your terminal. Now, let’s discover something more exciting: how to open a graphics window and draw inside? To start your journey in graphic programming, FdF offers to represent “iron wire” meshing in 3D.",
      difficulty: "beginner",
      estimatedHours: 60,
      baseXP: 1000,
      teamSize: { min: 1, max: 1 },
      subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/136326/en.subject.pdf",
      status: "not_started",
      tags: ["Simple graphic library", "Segment layout", "Events", "3D projection to 2D", "Rigor", "Algorithms & AI", "Imperative programming", "Graphics"],
      updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1471,
      id: "10",
      name: "push_swap",
      description:
        "This project involves sorting data on a stack, with a limited set of instructions, and the smallest number of moves. To make this happen, you will have to manipulate various sorting algorithms and choose the most appropriate solution(s) for optimized data sorting.",
      difficulty: "beginner",
      estimatedHours: 60,
      baseXP: 1855,
      teamSize: { min: 1, max: 1 },
      subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/143924/en.subject.pdf",
      status: "completed",
      tags: ["Sorting algorithms", "Battery concept and handling elements", "Algorithm implementation", "Rigor", "Unix", "Algorithms & AI", "Imperative programming"],
      updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1334,
        id: "11",
        name: "Philosophers",
        description:
          "This project aims to teach concurrent programming, focusing on multithreading and multiprocessing.",
        difficulty: "beginner",
        estimatedHours: 70,
        baseXP: 3360,
        teamSize: { min: 2, max: 2 },
        subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/147346/en.subject.pdf",
        status: "completed",
        tags: ["Unix logic", "Rigor", "Unix", "Imperative programming"],
        updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1331,
        id: "12",
        name: "minishell",
        description:
          "The objective of this project is for you to create a simple shell.",
        difficulty: "intermediate",
        estimatedHours: 210,
        baseXP: 2814,
        teamSize: { min: 2, max: 2 },
        subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/136337/en.subject.pdf",
        status: "completed",
        tags: ["Unix logic", "Rigor", "Unix", "Imperative programming"],
        updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1326,
        id: "13",
        name: "cub3d",
        description:
          "This project is inspired by the world-famous eponymous 90's game, which was the first FPS ever. It will enable you to explore ray-casting. Your goal will be to make a dynamic view inside a maze, in which you'll have to find your way.",
        difficulty: "intermediate",
        estimatedHours: 280,
        baseXP: 5775,
        teamSize: { min: 2, max: 2 },
        subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/134785/en.subject.pdf",
        status: "completed",
        tags: ["Applicative", "Rigor", "Algorithms & AI", "Imperative programming", "Graphics"],
        updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1315,
        id: "14",
        name: "miniRT",
        description:
          "This project is an introduction to the beautiful world of Raytracing.",
        difficulty: "intermediate",
        estimatedHours: 280,
        baseXP: 5775,
        teamSize: { min: 2, max: 2 },
        subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/147348/en.subject.pdf",
        status: "not_started",
        tags: ["Applicative", "Rigor", "Algorithms & AI", "Imperative programming", "Graphics"],
        updatedAt: new Date().toISOString(),
    },
    {
      project_id: 2007,
        id: "15",
        name: "NetPractice",
        description:
          "NetPractice is a general practical exercise to let you discover networking.",
        difficulty: "intermediate",
        estimatedHours: 50,
        baseXP: 3160,
        teamSize: { min: 1, max: 1 },
        subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/136343/en.subject.pdf",
        status: "completed",
        tags: ["Rigor", "Network & system administration"],
        updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1338,
        id: "16",
        name: "CPP Module 00",
        description:
          "This first module of C++ is designed to help you understand the specifities of the language when compared to C. Time to dive into Object Oriented Programming!",
        difficulty: "beginner",
        estimatedHours: 22,
        baseXP: 0,
        teamSize: { min: 1, max: 1 },
        subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/143922/en.subject.pdf",
        status: "completed",
        tags: ["Imperative programming", "Object-oriented programming", "Rigor"],
        updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1339,
        id: "17",
        name: "CPP Module 01",
        description:
          "This first module of C++ is designed to help you understand the specifities of the language when compared to C. Time to dive into Object Oriented Programming!",
        difficulty: "beginner",
        estimatedHours: 12,
        baseXP: 0,
        teamSize: { min: 1, max: 1 },
        subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/141056/en.subject.pdf",
        status: "completed",
        tags: ["Imperative programming", "Object-oriented programming", "Rigor"],
        updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1340,
        id: "18",
        name: "CPP Module 02",
        description:
          "This module is designed to help you understand Ad-hoc polymorphism, overloads and orthodox canonical classes in CPP.",
        difficulty: "beginner",
        estimatedHours: 12,
        baseXP: 0,
        teamSize: { min: 1, max: 1 },
        subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/143910/en.subject.pdf",
        status: "completed",
        tags: ["Imperative programming", "Object-oriented programming", "Rigor"],
        updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1341,
        id: "19",
        name: "CPP Module 03",
        description:
          "This module is designed to help you understand Inheritance in CPP.",
        difficulty: "beginner",
        estimatedHours: 12,
        baseXP: 0,
        teamSize: { min: 1, max: 1 },
        subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/141059/en.subject.pdf",
        status: "completed",
        tags: ["Imperative programming", "Object-oriented programming", "Rigor"],
        updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1342,
        id: "20",
        name: "CPP Module 04",
        description:
          "This module is designed to help you understand Inheritance in CPP.",
        difficulty: "beginner",
        estimatedHours: 12,
        baseXP: 9660,
        teamSize: { min: 1, max: 1 },
        subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/141060/en.subject.pdf",
        status: "completed",
        tags: ["Imperative programming", "Object-oriented programming", "Rigor"],
        updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1343,
        id: "21",
        name: "CPP Module 05",
        description:
          "This module is designed to help you understand Try/Catch and Exceptions in CPP.",
        difficulty: "beginner",
        estimatedHours: 25,
        baseXP: 0,
        teamSize: { min: 1, max: 1 },
        subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/143928/en.subject.pdf",
        status: "completed",
        tags: ["Imperative programming", "Object-oriented programming", "Rigor"],
        updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1344,
        id: "22",
        name: "CPP Module 06",
        description:
          "This module is designed to help you understand the different casts in CPP.",
        difficulty: "beginner",
        estimatedHours: 25,
        baseXP: 0,
        teamSize: { min: 1, max: 1 },
        subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/141063/en.subject.pdf",
        status: "completed",
        tags: ["Imperative programming", "Object-oriented programming", "Rigor"],
        updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1345,
        id: "23",
        name: "CPP Module 07",
        description:
          "This module is designed to help you understand Templates in CPP.",
        difficulty: "beginner",
        estimatedHours: 25,
        baseXP: 0,
        teamSize: { min: 1, max: 1 },
        subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/141064/en.subject.pdf",
        status: "completed",
        tags: ["Imperative programming", "Object-oriented programming", "Rigor"],
        updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1346,
        id: "24",
        name: "CPP Module 08",
        description:
          "This module is designed to help you understand templated containers, iterators and algorithms in CPP.",
        difficulty: "beginner",
        estimatedHours: 25,
        baseXP: 0,
        teamSize: { min: 1, max: 1 },
        subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/141065/en.subject.pdf",
        status: "completed",
        tags: ["Imperative programming", "Object-oriented programming", "Rigor"],
        updatedAt: new Date().toISOString(),
    },
    {
      project_id: 2309,
        id: "25",
        name: "CPP Module 09",
        description:
          "This module is designed to help you understand the containers in CPP.",
        difficulty: "beginner",
        estimatedHours: 40,
        baseXP: 10042,
        teamSize: { min: 1, max: 1 },
        subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/139792/en.subject.pdf",
        status: "completed",
        tags: ["Imperative programming", "Object-oriented programming", "Rigor"],
        updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1983,
        id: "26",
        name: "Inception",
        description:
          "This project aims to broaden your knowledge of system administration by using Docker. You will virtualize several Docker images, creating them in your new personal virtual machine.",
        difficulty: "intermediate",
        estimatedHours: 210,
        baseXP: 10042,
        teamSize: { min: 1, max: 1 },
        subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/147349/en.subject.pdf",
        status: "completed",
        tags: ["System administration", "Rigor", "Network & system administration"],
        updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1336,
        id: "27",
        name: "ft_irc",
        description:
          "Create your own IRC server in C++, fully compatible with an official client.",
        difficulty: "advanced",
        estimatedHours: 175,
        baseXP: 21630,
        teamSize: { min: 2, max: 3 },
        subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/147356/en.subject.pdf",
        status: "not_started",
        tags: ["Rigor", "Unix", "Network & system administration", "Object-oriented programming"],
        updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1332,
        id: "28",
        name: "webserv",
        description:
          "This project is here to make you write your own HTTP server. You will be able to test it with a real browser. HTTP is one of the most used protocol on internet. Knowing its arcane will be useful, even if you won't be working on a website.",
        difficulty: "advanced",
        estimatedHours: 175,
        baseXP: 21630,
        teamSize: { min: 2, max: 3 },
        subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/139962/en.subject.pdf",
        status: "not_started",
        tags: ["Rigor", "Unix", "Network & system administration", "Object-oriented programming"],
        updatedAt: new Date().toISOString(),
    },
    {
      project_id: 1337,
        id: "29",
        name: "ft_transcendence",
        description:
          "This project is centered around the design, development, and organization of a full-stack web application.",
        difficulty: "advanced",
        estimatedHours: 245,
        baseXP: 24360,
        teamSize: { min: 3, max: 5 },
        oldSubject: "https://codeberg.org/adrien-lsh/42-ft_transcendence/media/branch/main/subject.pdf",
        subjectUrl: "https://cdn.intra.42.fr/pdf/pdf/150347/en.subject.pdf",
        status: "not_started",
        tags: ["Specs", "Rigor", "Web", "Group & interpersonal"],
        updatedAt: new Date().toISOString(),
    },
  ];
  
