import { Project, XPEntry } from "@/types/xp";

export const mockProjects: Project[] = [
  { id: "libft", name: "Libft", baseXP: 462 },
  { id: "ft_printf", name: "ft_printf", baseXP: 882 },
  { id: "get_next_line", name: "get_next_line", baseXP: 882 },
  { id: "born2beroot", name: "Born2beroot", baseXP: 577 },
  { id: "pipex", name: "pipex", baseXP: 1142 },
  { id: "minitalk", name: "minitalk", baseXP: 1142 },
  { id: "so_long", name: "so_long", baseXP: 1000 },
  { id: "fdf", name: "Fdf", baseXP: 1000 },
  { id: "fract-ol", name: "fract-ol", baseXP: 1000 },
  { id: "push_swap", name: "push_swap", baseXP: 1855 },
  { id: "philosophers", name: "Philosophers", baseXP: 3360 },
  { id: "minishell", name: "minishell", baseXP: 2814 },
  { id: "cub3d", name: "cub3d", baseXP: 5775 },
  { id: "miniRT", name: "miniRT", baseXP: 5775 },
  { id: "netPractice", name: "NetPractice", baseXP: 3160 },
  { id: "cpp04", name: "CPP Module 04", baseXP: 9660 },
  { id: "cpp09", name: "CPP Module 09", baseXP: 10042 },
  { id: "inception", name: "Inception", baseXP: 10042 },
  { id: "ft_irc", name: "ft_irc", baseXP: 21630 },
  { id: "webserv", name: "webserv", baseXP: 21630 },
  { id: "ft_transcendence", name: "ft_transcendence", baseXP: 24360 },
  { id: "internship1", name: "Internship I", baseXP: 42000 },
  { id: "internship2", name: "Internship II", baseXP: 63000 },
  { id: "startup_internship", name: "Startup Internship", baseXP: 42000 },
  { id: "42run", name: "42run", baseXP: 9450 },
  { id: "42sh", name: "42sh", baseXP: 15750 },
  { id: "abstract_data", name: "Abstract_data", baseXP: 20084 },
  { id: "abstract-vm", name: "abstract-vm", baseXP: 9450 },
  { id: "amazon", name: "Amazon", baseXP: 15750 },
  { id: "avaj-launcher", name: "avaj-launcher", baseXP: 4200 },
  {
    id: "bgp_at_doors_of_autonomous_systems_is_simple",
    name: "Bgp At Doors of Autonomous Systems is Simple",
    baseXP: 22450,
  },
  { id: "bomberman", name: "bomberman", baseXP: 25200 },
  { id: "boot2root", name: "boot2root", baseXP: 11500 },
  { id: "camagru", name: "camagru", baseXP: 4200 },
  { id: "churn", name: "churn", baseXP: 9450 },
  { id: "cinema", name: "cinema", baseXP: 9450 },
  { id: "city_life", name: "City Life", baseXP: 15750 },
  { id: "cloud-1", name: "cloud-1", baseXP: 9450 },
  { id: "computorv1", name: "computorv1", baseXP: 4200 },
  { id: "computorv2", name: "computorv2", baseXP: 9450 },
  { id: "corewar", name: "corewar", baseXP: 17500 },
  {
    id: "cybersecurity_-_arachnida_-_web",
    name: "Cybersecurity - arachnida - Web",
    baseXP: 1350,
  },
  {
    id: "cybersecurity_-_ft_onion_-_web",
    name: "Cybersecurity - ft_onion - Web",
    baseXP: 1350,
  },
  {
    id: "cybersecurity_-_ft_otp_-_otp",
    name: "Cybersecurity - ft_otp - OTP",
    baseXP: 1350,
  },
  {
    id: "cybersecurity_-_inquisitor_-_network",
    name: "Cybersecurity - Inquisitor - Network",
    baseXP: 1350,
  },
  {
    id: "cybersecurity_-_reverse_me_-_rev",
    name: "Cybersecurity - Reverse me - Rev",
    baseXP: 1350,
  },
  {
    id: "cybersecurity_-_stockholm_-_malware",
    name: "Cybersecurity - Stockholm - Malware",
    baseXP: 1350,
  },
  {
    id: "cybersecurity_-_vaccine_-_web",
    name: "Cybersecurity - Vaccine - Web",
    baseXP: 1350,
  },
  { id: "darkly", name: "darkly", baseXP: 6300 },
  { id: "data_science_-_0", name: "Data Science - 0", baseXP: 545 },
  { id: "data_science_-_1", name: "Data Science - 1", baseXP: 545 },
  { id: "data_science_-_2", name: "Data Science - 2", baseXP: 545 },
  { id: "data_science_-_3", name: "Data Science - 3", baseXP: 545 },
  { id: "data_science_-_4", name: "Data Science - 4", baseXP: 2545 },
  { id: "death", name: "death", baseXP: 35700 },
  {
    id: "django_-_1_-_base_django",
    name: "Django - 1 - Base Django",
    baseXP: 3475,
  },
  { id: "django_-_2_-_sql", name: "Django - 2 - SQL", baseXP: 1000 },
  {
    id: "django_-_3_-_final",
    name: "Django - 3 - Final",
    baseXP: 3475,
  },
  { id: "doom-nukem", name: "doom-nukem", baseXP: 15750 },
  {
    id: "drivers-and-interrupts",
    name: "drivers-and-interrupts",
    baseXP: 15750,
  },
  { id: "dr-quine", name: "dr-quine", baseXP: 2520 },
  { id: "dslr", name: "dslr", baseXP: 6000 },
  { id: "expert-system", name: "expert-system", baseXP: 9450 },
  { id: "famine", name: "famine", baseXP: 9450 },
  { id: "filesystem", name: "filesystem", baseXP: 15750 },
  { id: "fix-me", name: "fix-me", baseXP: 15750 },
  { id: "fried_eggs", name: "Fried eggs", baseXP: 25200 },
  { id: "ft_ality", name: "ft_ality", baseXP: 4200 },
  { id: "ft_hangouts", name: "ft_hangouts", baseXP: 4200 },
  { id: "ft_kalman", name: "ft_kalman", baseXP: 16800 },
  {
    id: "ft_linear_regression",
    name: "ft_linear_regression",
    baseXP: 4200,
  },
  { id: "ft_linux", name: "ft_linux", baseXP: 4200 },
  { id: "ftl_quantum", name: "Ftl_quantum", baseXP: 6500 },
  { id: "ft_ls", name: "ft_ls", baseXP: 4200 },
  { id: "ft_microservices", name: "ft_microservices", baseXP: 4200 },
  { id: "ft_minecraft", name: "ft_minecraft", baseXP: 20750 },
  { id: "ft_newton", name: "ft_newton", baseXP: 24360 },
  { id: "ft_nmap", name: "ft_nmap", baseXP: 15750 },
  { id: "ft_ping", name: "ft_ping", baseXP: 4200 },
  { id: "ft_script", name: "ft_script", baseXP: 4200 },
  { id: "ft_select", name: "ft_select", baseXP: 4200 },
  { id: "ft_server", name: "ft_server", baseXP: 1722 },
  { id: "ft_services", name: "ft_services", baseXP: 10042 },
  { id: "ft_shield", name: "ft_shield", baseXP: 15750 },
  { id: "ft_ssl_des", name: "ft_ssl_des", baseXP: 9450 },
  { id: "ft_ssl_md5", name: "ft_ssl_md5", baseXP: 9450 },
  { id: "ft_ssl_rsa", name: "ft_ssl_rsa", baseXP: 15750 },
  { id: "ft_traceroute", name: "ft_traceroute", baseXP: 4200 },
  { id: "ft_turing", name: "ft_turing", baseXP: 9450 },
  { id: "ft_vox", name: "ft_vox", baseXP: 15750 },
  { id: "fwa", name: "fwa", baseXP: 4200 },
  { id: "gbmu", name: "gbmu", baseXP: 31500 },
  { id: "gomoku", name: "gomoku", baseXP: 25200 },
  { id: "guimp", name: "guimp", baseXP: 12600 },
  { id: "h42n42", name: "h42n42", baseXP: 9450 },
  { id: "humangl", name: "humangl", baseXP: 4200 },
  { id: "hypertube", name: "hypertube", baseXP: 15750 },
  {
    id: "inception-of-things",
    name: "Inception-of-Things",
    baseXP: 25450,
  },
  { id: "in-the-shadows", name: "in-the-shadows", baseXP: 9450 },
  { id: "java_module_09", name: "Java Module 09", baseXP: 15750 },
  { id: "kfs-1", name: "kfs-1", baseXP: 15750 },
  { id: "kfs-2", name: "kfs-2", baseXP: 15750 },
  { id: "kfs-3", name: "kfs-3", baseXP: 35700 },
  { id: "kfs-4", name: "kfs-4", baseXP: 25200 },
  { id: "kfs-5", name: "kfs-5", baseXP: 35700 },
  { id: "kfs-6", name: "kfs-6", baseXP: 25200 },
  { id: "kfs-7", name: "kfs-7", baseXP: 35700 },
  { id: "kfs-8", name: "kfs-8", baseXP: 15750 },
  { id: "kfs-9", name: "kfs-9", baseXP: 15750 },
  { id: "kfs-x", name: "kfs-x", baseXP: 35700 },
  { id: "krpsim", name: "krpsim", baseXP: 9450 },
  { id: "leaffliction", name: "Leaffliction", baseXP: 15750 },
  { id: "learn2slither", name: "Learn2Slither", baseXP: 9450 },
  { id: "lem_in", name: "lem_in", baseXP: 9450 },
  { id: "lem-ipc", name: "lem-ipc", baseXP: 9450 },
  { id: "libasm", name: "libasm", baseXP: 966 },
  { id: "libftpp", name: "libftpp", baseXP: 5880 },
  { id: "little-penguin-1", name: "little-penguin-1", baseXP: 9450 },
  { id: "malloc", name: "malloc", baseXP: 9450 },
  { id: "matcha", name: "matcha", baseXP: 9450 },
  { id: "matrix", name: "matrix", baseXP: 7000 },
  { id: "matt-daemon", name: "matt-daemon", baseXP: 9450 },
  { id: "messagequeue", name: "messagequeue", baseXP: 9450 },
  { id: "microshop", name: "Microshop", baseXP: 24360 },
  {
    id: "mobile_-_0_-_basic_of_the_mobile_application",
    name: "Mobile - 0 - Basic of the mobile application",
    baseXP: 500,
  },
  {
    id: "mobile_-_1_-_structure_and_logic",
    name: "Mobile - 1 - Structure and logic",
    baseXP: 950,
  },
  {
    id: "mobile_-_2_-_api_and_data",
    name: "Mobile - 2 - API and data",
    baseXP: 1000,
  },
  {
    id: "mobile_-_3_-_design",
    name: "Mobile - 3 - Design",
    baseXP: 2000,
  },
  {
    id: "mobile_-_4_-_auth_and_database",
    name: "Mobile - 4 - Auth and dataBase",
    baseXP: 2000,
  },
  {
    id: "mobile_-_5_-_manage_data_and_display",
    name: "Mobile - 5 - Manage data and display",
    baseXP: 3000,
  },
  { id: "mod1", name: "mod1", baseXP: 9450 },
  {
    id: "multilayer-perceptron",
    name: "multilayer-perceptron",
    baseXP: 9450,
  },
  { id: "music-room", name: "music-room", baseXP: 25200 },
  { id: "myspotify", name: "mySpotify", baseXP: 9450 },
  { id: "nibbler", name: "nibbler", baseXP: 9450 },
  { id: "nm", name: "nm", baseXP: 9450 },
  { id: "n-puzzle", name: "n-puzzle", baseXP: 9450 },
  {
    id: "ocaml_-_functor_-_1",
    name: "OCAML - Functor - 1",
    baseXP: 2250,
  },
  {
    id: "ocaml_-_monoids_and_monads_-_3",
    name: "OCAML - Monoids and Monads - 3",
    baseXP: 3475,
  },
  {
    id: "ocaml_-_object_oriented_programming_-_2",
    name: "OCAML - Object Oriented Programming - 2",
    baseXP: 2225,
  },
  {
    id: "ocaml_-_pattern_matching_and_data_types_-_0",
    name: "OCAML - Pattern Matching and Data Types - 0",
    baseXP: 1500,
  },
  { id: "open_project", name: "Open Project", baseXP: 31500 },
  { id: "override", name: "override", baseXP: 35700 },
  { id: "particle-system", name: "particle-system", baseXP: 15750 },
  { id: "peace_break", name: "Peace_Break", baseXP: 9000 },
  { id: "pestilence", name: "pestilence", baseXP: 15750 },
  {
    id: "piscine_object_-_module_00_-_encapsulation",
    name: "Piscine Object - Module 00 - Encapsulation",
    baseXP: 945,
  },
  {
    id: "piscine_object_-_module_01_-_relationship",
    name: "Piscine Object - Module 01 - Relationship",
    baseXP: 945,
  },
  {
    id: "piscine_object_-_module_02_-_uml",
    name: "Piscine Object - Module 02 - UML",
    baseXP: 1890,
  },
  {
    id: "piscine_object_-_module_03_-_solid",
    name: "Piscine Object - Module 03 - SOLID",
    baseXP: 1890,
  },
  {
    id: "piscine_object_-_module_04_-_design_pattern",
    name: "Piscine Object - Module 04 - Design Pattern",
    baseXP: 1890,
  },
  {
    id: "piscine_object_-_module_05_-_practical_work",
    name: "Piscine Object - Module 05 - Practical work",
    baseXP: 1890,
  },
  {
    id: "piscine_php_symfony",
    name: "Piscine PHP Symfony",
    baseXP: 9450,
  },
  {
    id: "piscine_ruby_on_rails",
    name: "Piscine Ruby on Rails",
    baseXP: 9450,
  },
  {
    id: "process-and-memory",
    name: "process-and-memory",
    baseXP: 9450,
  },
  {
    id: "python_-_0_-_starting",
    name: "Python - 0 - Starting",
    baseXP: 545,
  },
  { id: "python_-_1_-_array", name: "Python - 1 - Array", baseXP: 545 },
  {
    id: "python_-_2_-_datatable",
    name: "Python - 2 - DataTable",
    baseXP: 545,
  },
  { id: "python_-_3_-_oop", name: "Python - 3 - OOP", baseXP: 545 },
  { id: "python_-_4_-_dod", name: "Python - 4 - Dod", baseXP: 2545 },
  { id: "rainfall", name: "rainfall", baseXP: 25200 },
  { id: "ready_set_boole", name: "ready set boole", baseXP: 7000 },
  { id: "red-tetris", name: "red-tetris", baseXP: 15750 },
  { id: "restful", name: "restful", baseXP: 4200 },
  { id: "ror_-_0_-_oob", name: "RoR - 0 - Oob", baseXP: 1500 },
  {
    id: "ror_-_1_-_base_rails",
    name: "RoR - 1 - Base Rails",
    baseXP: 3475,
  },
  { id: "ror_-_2_-_sql", name: "RoR - 2 - SQL", baseXP: 1000 },
  { id: "ror_-_3_-_final", name: "RoR - 3 - Final", baseXP: 3475 },
  { id: "rt", name: "rt", baseXP: 20750 },
  { id: "rubik", name: "rubik", baseXP: 9450 },
  { id: "scop", name: "scop", baseXP: 9450 },
  { id: "shaderpixel", name: "shaderpixel", baseXP: 15750 },
  { id: "snow-crash", name: "snow-crash", baseXP: 9450 },
  { id: "spring_boot", name: "Spring Boot", baseXP: 15750 },
  { id: "strace", name: "strace", baseXP: 9450 },
  { id: "swifty-companion", name: "swifty-companion", baseXP: 4200 },
  { id: "swifty-proteins", name: "swifty-proteins", baseXP: 15750 },
  { id: "swingy", name: "swingy", baseXP: 9450 },
  { id: "symfony_-_0_-_oob", name: "Symfony - 0 - Oob", baseXP: 1500 },
  {
    id: "symfony_-_1_-_base_symfony",
    name: "Symfony - 1 - Base Symfony",
    baseXP: 3475,
  },
  { id: "symfony_-_2_-_sql", name: "Symfony - 2 - SQL", baseXP: 1000 },
  {
    id: "symfony_-_3_-_final",
    name: "Symfony - 3 - Final",
    baseXP: 3475,
  },
  { id: "taskmaster", name: "taskmaster", baseXP: 9450 },
  { id: "tinky-winkey", name: "tinky-winkey", baseXP: 16800 },
  { id: "tokenizeart", name: "TokenizeArt", baseXP: 9450 },
  { id: "tokenizer", name: "Tokenizer", baseXP: 9450 },
  {
    id: "total-perspective-vortex",
    name: "total-perspective-vortex",
    baseXP: 9450,
  },
  { id: "uber", name: "Uber", baseXP: 9450 },
  {
    id: "understanding_customer",
    name: "Understanding customer",
    baseXP: 9450,
  },
  {
    id: "unity_-_0_-_the_basics_unity_tools",
    name: "Unity - 0 - The basics Unity tools",
    baseXP: 500,
  },
  {
    id: "unity_-_1_-_3d_physics,_tags,_layers_and_scene",
    name: "Unity - 1 - 3D physics, Tags, Layers and Scene",
    baseXP: 500,
  },
  {
    id: "unity_-_2_-_2d_environment,_tiles_and_sprites",
    name: "Unity - 2 - 2D environment, tiles and sprites",
    baseXP: 1000,
  },
  {
    id: "unity_-_3_-_advanced_inputs_and_2d_gui",
    name: "Unity - 3 - Advanced inputs and 2D GUI",
    baseXP: 1000,
  },
  {
    id: "unity_-_4_-_animations_and_sound",
    name: "Unity - 4 - Animations and Sound",
    baseXP: 1000,
  },
  {
    id: "unity_-_5_-_singleton,_playerprefs_and_coroutines",
    name: "Unity - 5 - Singleton, playerPrefs and coroutines",
    baseXP: 2000,
  },
  {
    id: "unity_-_6_-_navmesh,_light,_sound_and_camera",
    name: "Unity - 6 - Navmesh, light, sound and camera",
    baseXP: 3450,
  },
  { id: "unleashthebox", name: "UnleashTheBox", baseXP: 15750 },
  {
    id: "userspace_digressions",
    name: "userspace_digressions",
    baseXP: 16800,
  },
  { id: "very_real_engine", name: "Very_Real_Engine", baseXP: 30000 },
  { id: "war", name: "war", baseXP: 35700 },
  { id: "woody-woodpacker", name: "woody-woodpacker", baseXP: 9450 },
  { id: "xv", name: "xv", baseXP: 22000 },
  { id: "zappy", name: "zappy", baseXP: 25200 },
];

export const levelsXp = [
  0, 462, 2688, 5885, 11777, 29217, 46255, 63559, 74340, 85483, 95000, 105630,
  124446, 145782, 169932, 197316, 228354, 263508, 303366, 348516, 399672,
  457632, 523320, 597786, 682164, 777756, 886074, 1008798, 1147902, 1305486,
  1484070, 9007199254740991,
];

export function calculateTotalXP(entries: XPEntry[]): number {
  return entries.reduce((sum, entry) => sum + entry.totalXP, 0);
}

export function calculateLevel(totalXP: number): number {
  return Math.floor(totalXP / 10000) + 1;
}

export function calculateProjectXP(
  project: Project,
  score: number,
  hasBonus: boolean
): number {
  const baseXP = (project.baseXP * Math.min(score, 125)) / 100;
  return hasBonus ? baseXP * 1.042 : baseXP;
}
